<?php
// ---- includes/stdFunc/pageRoutes.php --- lap 5.0.0 --- 2026.10.06 ---
// LICENSE
//
// This program is free software. You can redistribute it and / or
// modify it under the terms of the GNU General Public License (GPL)
// which is published by The Free Software Foundation; either in version 2
// of this license or later version of your choice.
// However, respect the following:
//
// It is forbidden to use this program in competition with Saldi.DK ApS
// or other proprietor of the program without prior written agreement.
//
// The program is published with the hope that it will be beneficial,
// but WITHOUT ANY KIND OF CLAIM OR WARRANTY. See
// GNU General Public License for more details.
//
// Copyright (c) 2026 saldi.dk aps
// ----------------------------------------------------------------------
// 20261006 Sawaneh The central breadcrumb map (topbar addendum 2026-10-05 §3, Adam 2026-10-06: breadcrumbs on every
//                  page). 'pages': 'dir/file.php' (or 'dir/file.php?param=value' for a variant of the same file) =>
//                  module 'm', label 'l' ('textId|Danish'; '|Text' without an id) and parent page 'p' from the Saldi
//                  root ('' = directly under the module). Read by page_auto_breadcrumb() in pageChrome.php.

return array(
	'modules' => array(
		'finans'     => array('l' => '600|Finans', 'href' => ''),
		'debitor'    => array('l' => '604|Debitor', 'href' => ''),
		'booking'    => array('l' => '1116|Booking', 'href' => ''),
		'kreditor'   => array('l' => '607|Kreditorer', 'href' => ''),
		'lager'      => array('l' => '608|Lager', 'href' => ''),
		'system'     => array('l' => '122|Indstillinger', 'href' => '/systemdata/settings.php'),
		'pos'        => array('l' => '5606|Kassesystem', 'href' => '/debitor/pos_ordre.php'),
		'sager'      => array('l' => '5607|Sagsstyring', 'href' => '/sager/sager.php'),
		'loen'       => array('l' => '2784|Løn', 'href' => '/sager/loen.php'),
		'produktion' => array('l' => '|Produktion', 'href' => ''),
	),
	// Step 2 (the breadcrumb replaces the old Luk/Tilbage): modules done so far, and pages that keep their button.
	// The cash journal waits for Saul's SD-712 release (15/10).
	'migrated' => array(
		'modules' => array('finans', 'debitor', 'kreditor', 'lager', 'produktion', 'system', 'booking'),
		'keep' => array('finans/kassekladde.php', 'finans/kladdeliste.php', 'finans/bogfor.php'),
	),
	// A page that is not in 'pages' shows its folder's module and its title.
	'dirs' => array('finans' => 'finans', 'bank_integration' => 'finans', 'debitor' => 'debitor', 'kreditor' => 'kreditor', 'lager' => 'lager',
		'produktion' => 'produktion', 'systemdata' => 'system', 'admin' => 'system', 'rental' => 'booking', 'sager' => 'sager', 'bordplaner' => 'pos'),
	'pages' => array(
		// finans/
		'finans/kladdeliste.php'               => array('m' => 'finans', 'l' => '639|Kladdeliste', 'p' => ''),
		'finans/kassekladde.php'               => array('m' => 'finans', 'l' => '1072|Kassekladde', 'p' => '/finans/kladdeliste.php'),
		'finans/bogfor.php'                    => array('m' => 'finans', 'l' => '2209|Bogfør kassekladde', 'p' => '/finans/kassekladde.php'),
		'finans/autoudlign.php'                => array('m' => 'finans', 'l' => '1066|Udlign', 'p' => '/finans/kassekladde.php'),
		'finans/hentordrer.php'                => array('m' => 'finans', 'l' => '|Hent ordrer', 'p' => '/finans/kassekladde.php'),
		'finans/importer.php'                  => array('m' => 'finans', 'l' => '1074|Importer', 'p' => '/finans/kassekladde.php'),
		'finans/bankimport.php'                => array('m' => 'finans', 'l' => '1391|Bankimport', 'p' => '/finans/importer.php'),
		'finans/danlonimport.php'              => array('m' => 'finans', 'l' => '1079|Import fra Danløn', 'p' => '/finans/importer.php'),
		'finans/datalonimport.php'             => array('m' => 'finans', 'l' => '1080|Import fra Dataløn', 'p' => '/finans/importer.php'),
		'finans/pbsm602import.php'             => array('m' => 'finans', 'l' => '|Importer til kassekladde', 'p' => '/finans/importer.php'),
		'finans/pbswebimport.php'              => array('m' => 'finans', 'l' => '|Importer til kassekladde', 'p' => '/finans/importer.php'),
		'finans/loppeafregning.php'            => array('m' => 'finans', 'l' => '|Loppeafregning', 'p' => '/finans/importer.php'),
		'finans/moms_periode.php'              => array('m' => 'finans', 'l' => '3366|Momsperioder', 'p' => '/finans/kladdeliste.php'),
		'finans/regnskab.php'                  => array('m' => 'finans', 'l' => '849|Regnskab', 'p' => ''),
		'finans/budget.php'                    => array('m' => 'finans', 'l' => '1067|Budget', 'p' => '/finans/regnskab.php'),
		'finans/kontospec.php'                 => array('m' => 'finans', 'l' => '1196|Specifikation for', 'p' => '/finans/regnskab.php'),
		'finans/rapport.php'                   => array('m' => 'finans', 'l' => '3359|Finansrapporter', 'p' => ''),
		'finans/kontokort_standalone.php'      => array('m' => 'finans', 'l' => '2173|Rapport - kontokort', 'p' => '/finans/rapport.php'),
		'finans/kontokort_moms_standalone.php' => array('m' => 'finans', 'l' => '516|Kontokort med moms', 'p' => '/finans/rapport.php'),
		'finans/kontrolspor.php'               => array('m' => 'finans', 'l' => '905|Kontrolspor', 'p' => '/finans/rapport.php'),
		'finans/listeangivelse.php'            => array('m' => 'finans', 'l' => '|Listeangivelse', 'p' => '/finans/rapport.php'),
		'finans/provisionsrapport.php'         => array('m' => 'finans', 'l' => '906|Provisionsrapport', 'p' => '/finans/rapport.php'),
		'finans/regnskabbasis.php'             => array('m' => 'finans', 'l' => '2326|Regnskab Basis', 'p' => '/finans/rapport.php'),
		'finans/saft.php'                      => array('m' => 'finans', 'l' => '2320|SAF-T', 'p' => '/finans/rapport.php'),
		'finans/bankReconcile.php'             => array('m' => 'finans', 'l' => '2213|Bankafstemning', 'p' => '/finans/rapport.php'),

		// bank_integration/
		'bank_integration/aiia_import.php'     => array('m' => 'finans', 'l' => '1391|Bankimport', 'p' => '/finans/kassekladde.php'),
		'bank_integration/get_accounts.php'    => array('m' => 'finans', 'l' => '|Vælg bankkonto', 'p' => '/finans/kassekladde.php'),

		// admin/
		'admin/backup.php'                     => array('m' => 'system', 'l' => '614|Backup', 'p' => ''),
		'admin/restore.php'                    => array('m' => 'system', 'l' => '1247|Indlæs sikkerhedskopi', 'p' => ''),
		// debitor/
		'debitor/debitor.php' => array('m' => 'debitor', 'l' => '117|Konti', 'p' => ''),
		'debitor/debitor.php?valg=historik' => array('m' => 'debitor', 'l' => '907|Historik', 'p' => '/debitor/debitor.php', 'q' => array('valg' => 'historik')),
		'debitor/debitor.php?valg=kommission' => array('m' => 'debitor', 'l' => '909|Kommission', 'p' => '/debitor/debitor.php', 'q' => array('valg' => 'kommission')),
		'debitor/debitor.php?valg=rental' => array('m' => 'booking', 'l' => '1116|Booking', 'p' => '', 'q' => array('valg' => 'rental')),
		'debitor/debitor_historik.php' => array('m' => 'debitor', 'l' => '907|Historik', 'p' => '/debitor/debitor.php'),
		'debitor/debitor_kommission.php' => array('m' => 'debitor', 'l' => '909|Kommission', 'p' => '/debitor/debitor.php'),
		'debitor/debitorvisning.php' => array('m' => 'debitor', 'l' => '911|Debitorlistevisning', 'p' => '/debitor/debitor.php'),
		'debitor/debitorvisning.php?valg=historik' => array('m' => 'debitor', 'l' => '1129|Historikvisning', 'p' => '/debitor/debitor.php?valg=historik', 'q' => array('valg' => 'historik')),
		'debitor/debitorkort.php' => array('m' => 'debitor', 'l' => '356|Debitorkort', 'p' => '/debitor/debitor.php'),
		'debitor/ansatte.php' => array('m' => 'debitor', 'l' => '1262|Ansatte', 'p' => '/debitor/debitorkort.php'),
		'debitor/kontofusion.php' => array('m' => 'debitor', 'l' => '|Fusioner debitorer', 'p' => '/debitor/debitorkort.php'),
		'debitor/historikkort.php' => array('m' => 'debitor', 'l' => '1668|Historik for debitor', 'p' => '/debitor/debitor.php?valg=historik'),
		'debitor/jobliste.php' => array('m' => 'debitor', 'l' => '38|Opgaveliste', 'p' => '/debitor/debitor.php'),
		'debitor/jobkort.php' => array('m' => 'debitor', 'l' => '29|Jobkort', 'p' => '/debitor/jobliste.php'),
		'debitor/rental.php' => array('m' => 'booking', 'l' => '2050|Udlejning', 'p' => '/debitor/debitor.php?valg=rental'),
		'debitor/ordreliste.php' => array('m' => 'debitor', 'l' => '605|Ordre', 'p' => ''),
		'debitor/ordreliste.php?valg=ordrer' => array('m' => 'debitor', 'l' => '107|Ordrer', 'p' => '', 'q' => array('valg' => 'ordrer')),
		'debitor/ordreliste.php?valg=tilbud' => array('m' => 'debitor', 'l' => '2770|Tilbud', 'p' => '', 'q' => array('valg' => 'tilbud')),
		'debitor/ordreliste.php?valg=faktura' => array('m' => 'debitor', 'l' => '1777|Fakturaer', 'p' => '', 'q' => array('valg' => 'faktura')),
		'debitor/ordreliste.php?valg=pbs' => array('m' => 'debitor', 'l' => '385|BS', 'p' => '', 'q' => array('valg' => 'pbs')),
		'debitor/ordrevisning.php' => array('m' => 'debitor', 'l' => '546|Ordrevisning', 'p' => '/debitor/ordreliste.php'),
		'debitor/ordre.php' => array('m' => 'debitor', 'l' => '1092|Kundeordre', 'p' => '/debitor/ordreliste.php'),
		'debitor/productLookup.php' => array('m' => 'debitor', 'l' => '|Vareopslag', 'p' => '/debitor/ordre.php'),
		'debitor/saetpris.php' => array('m' => 'debitor', 'l' => '2115|Sætpris', 'p' => '/debitor/ordre.php'),
		'debitor/udskriftsvalg.php' => array('m' => 'debitor', 'l' => '|Udskriftsvalg', 'p' => '/debitor/ordre.php'),
		'debitor/stockWarningLog.php' => array('m' => 'debitor', 'l' => '|Salg af udsolgte varer - godkendelser', 'p' => '/debitor/ordre.php'),
		'debitor/fakturadato.php' => array('m' => 'debitor', 'l' => '1094|Fakturadato', 'p' => '/debitor/ordre.php'),
		'debitor/csv2ordre.php' => array('m' => 'debitor', 'l' => '|Importer ordrer fra CSV', 'p' => '/debitor/ordreliste.php'),
		'debitor/massefakt.php' => array('m' => 'debitor', 'l' => '200|Massefakturering', 'p' => '/debitor/ordreliste.php'),
		'debitor/genfakturer.php' => array('m' => 'debitor', 'l' => '82|Genfakturer', 'p' => '/debitor/ordreliste.php?valg=faktura'),
		'debitor/ret_genfakt.php' => array('m' => 'debitor', 'l' => '|Ret abonnementsordrer', 'p' => '/debitor/ordreliste.php?valg=faktura'),
		'debitor/pbs_import.php' => array('m' => 'debitor', 'l' => '|Import fra PBS', 'p' => '/debitor/ordreliste.php?valg=pbs'),
		'debitor/pbsfile.php' => array('m' => 'debitor', 'l' => '|PBS', 'p' => '/debitor/ordreliste.php?valg=pbs'),
		'debitor/rapport.php' => array('m' => 'debitor', 'l' => '449|Debitorrapporter', 'p' => ''),
		'debitor/rapport.php?rapportart=openpost' => array('m' => 'debitor', 'l' => '441|Åbne poster', 'p' => '/debitor/rapport.php', 'q' => array('rapportart' => 'openpost')),
		'debitor/rapport.php?rapportart=kontokort' => array('m' => 'debitor', 'l' => '133|Kontokort', 'p' => '/debitor/rapport.php', 'q' => array('rapportart' => 'kontokort')),
		'debitor/rapport.php?rapportart=accountChart' => array('m' => 'debitor', 'l' => '133|Kontokort', 'p' => '/debitor/rapport.php', 'q' => array('rapportart' => 'accountChart')),
		'debitor/rapport.php?rapportart=kontosaldo' => array('m' => 'debitor', 'l' => '442|Kontosaldo', 'p' => '/debitor/rapport.php', 'q' => array('rapportart' => 'kontosaldo')),
		'debitor/rykker.php' => array('m' => 'debitor', 'l' => '1143|Rykkerbrev', 'p' => '/debitor/rapport.php?rapportart=openpost'),
		'debitor/betalingsliste.php' => array('m' => 'debitor', 'l' => '|Betalingsliste', 'p' => '/debitor/rapport.php'),
		'debitor/betalinger.php' => array('m' => 'debitor', 'l' => '2738|Betalinger til bank', 'p' => '/debitor/betalingsliste.php'),
		'debitor/mail_modtagere.php' => array('m' => 'debitor', 'l' => '|Mailmodtagere', 'p' => '/debitor/betalinger.php'),
		'debitor/kassespor.php' => array('m' => 'debitor', 'l' => '455|Kassespor', 'p' => '/debitor/rapport.php'),
		'debitor/saftCashRegister.php' => array('m' => 'debitor', 'l' => '2711|SAF-T kasserapport', 'p' => '/debitor/rapport.php'),
		'debitor/top100.php' => array('m' => 'debitor', 'l' => '448|Top 100', 'p' => '/debitor/rapport.php'),
		'debitor/postnr.php' => array('m' => 'debitor', 'l' => '|Top 100 Postnr', 'p' => '/debitor/rapport.php'),
		'debitor/salg_postnr.php' => array('m' => 'debitor', 'l' => '3360|Salg pr. postnummer', 'p' => '/debitor/rapport.php'),
		'debitor/multiroute.php' => array('m' => 'debitor', 'l' => '1654|Eksport til mulitroute', 'p' => '/debitor/rapport.php'),
		'debitor/crmkalender.php' => array('m' => 'debitor', 'l' => '|CRM', 'p' => ''),
		'debitor/crmvisning.php' => array('m' => 'debitor', 'l' => '813|Visning', 'p' => '/debitor/crmkalender.php'),
		'debitor/crmopret.php' => array('m' => 'debitor', 'l' => '1232|Opret', 'p' => '/debitor/crmkalender.php'),
		'debitor/pos_ordre.php' => array('m' => 'pos', 'l' => '5606|Kassesystem', 'p' => ''),
		'debitor/cashCountHistory.php' => array('m' => 'pos', 'l' => '|Tidligere kasseoptællinger', 'p' => '/debitor/pos_ordre.php'),
		// debitor/payments/
		'debitor/payments/lane3000_afstemning.php' => array('m' => 'pos', 'l' => '2257|Afstemning', 'p' => '/debitor/pos_ordre.php'),
		// kreditor/
		'kreditor/ordreliste.php' => array('m' => 'kreditor', 'l' => '605|Ordre', 'p' => ''),
		'kreditor/ordreliste.php?valg=forslag' => array('m' => 'kreditor', 'l' => '827|Forslag', 'p' => '', 'q' => array('valg' => 'forslag')),
		'kreditor/ordreliste.php?valg=faktura' => array('m' => 'kreditor', 'l' => '643|Faktura', 'p' => '', 'q' => array('valg' => 'faktura')),
		'kreditor/ordre.php' => array('m' => 'kreditor', 'l' => '547|Leverandørordre', 'p' => '/kreditor/ordreliste.php'),
		'kreditor/productLookup.php' => array('m' => 'kreditor', 'l' => '|Vareopslag', 'p' => '/kreditor/ordre.php'),
		'kreditor/ublimport.php' => array('m' => 'kreditor', 'l' => '|OIOUBL import', 'p' => '/kreditor/ordre.php'),
		'kreditor/orderIncludes/dropshipping.php' => array('m' => 'kreditor', 'l' => '|Adresseopslag', 'p' => '/kreditor/ordre.php'),
		'kreditor/kreditor.php' => array('m' => 'kreditor', 'l' => '2695|Kreditorliste', 'p' => ''),
		'kreditor/kreditorvisning.php' => array('m' => 'kreditor', 'l' => '1189|Kreditorvisning', 'p' => '/kreditor/kreditor.php'),
		'kreditor/kreditorkort.php' => array('m' => 'kreditor', 'l' => '1184|Kreditorkort', 'p' => '/kreditor/kreditor.php'),
		'kreditor/ansatte.php' => array('m' => 'kreditor', 'l' => '1262|Ansatte', 'p' => '/kreditor/kreditorkort.php'),
		'kreditor/kontofusion.php' => array('m' => 'kreditor', 'l' => '|Fusioner kreditorer', 'p' => '/kreditor/kreditorkort.php'),
		'kreditor/rapport.php' => array('m' => 'kreditor', 'l' => '450|Kreditorrapporter', 'p' => ''),
		'kreditor/rapport.php?rapportart=kontokort' => array('m' => 'kreditor', 'l' => '133|Kontokort', 'p' => '/kreditor/rapport.php', 'q' => array('rapportart' => 'kontokort')),
		'kreditor/rapport.php?rapportart=openpost' => array('m' => 'kreditor', 'l' => '441|Åbne poster', 'p' => '/kreditor/rapport.php', 'q' => array('rapportart' => 'openpost')),
		'kreditor/rapport.php?rapportart=kontosaldo' => array('m' => 'kreditor', 'l' => '442|Kontosaldo', 'p' => '/kreditor/rapport.php', 'q' => array('rapportart' => 'kontosaldo')),
		'kreditor/top100.php' => array('m' => 'kreditor', 'l' => '448|Top 100', 'p' => '/kreditor/rapport.php'),
		'kreditor/betalingsliste.php' => array('m' => 'kreditor', 'l' => '|Betalingsliste', 'p' => '/kreditor/rapport.php'),
		'kreditor/betalinger.php' => array('m' => 'kreditor', 'l' => '2738|Betalinger til bank', 'p' => '/kreditor/betalingsliste.php'),
		// lager/
		'lager/varer.php' => array('m' => 'lager', 'l' => '609|Varer', 'p' => ''),
		'lager/lister/vareliste.php' => array('m' => 'lager', 'l' => '957|Vareliste', 'p' => ''),
		'lager/lister/ordrestatus.php' => array('m' => 'lager', 'l' => '546|Ordrevisning', 'p' => ''),
		'lager/lister/indkøb.php' => array('m' => 'lager', 'l' => '5545|Indkøb', 'p' => ''),
		'lager/lister/serialnumber.php' => array('m' => 'lager', 'l' => '|Serienumre', 'p' => ''),
		'lager/lister/styklister.php' => array('m' => 'lager', 'l' => '|Styklister', 'p' => ''),
		'lager/varevisning.php' => array('m' => 'lager', 'l' => '563|Varevisning', 'p' => '/lager/varer.php'),
		'lager/lagerflyt.php' => array('m' => 'lager', 'l' => '|Flyt vare', 'p' => '/lager/varer.php'),
		'lager/varekort.php' => array('m' => 'lager', 'l' => '566|Varekort', 'p' => '/lager/varer.php'),
		'lager/ret_varenr.php' => array('m' => 'lager', 'l' => '|Ret varenummer', 'p' => '/lager/varekort.php'),
		'lager/ret_varenralias.php' => array('m' => 'lager', 'l' => '|Ret varenummer alias', 'p' => '/lager/varekort.php'),
		'lager/varefoto.php' => array('m' => 'lager', 'l' => '|Varefoto', 'p' => '/lager/varekort.php'),
		'lager/happyhour.php' => array('m' => 'lager', 'l' => '|HappyHour', 'p' => '/lager/varekort.php'),
		'lager/emballage.php' => array('m' => 'lager', 'l' => '|Emballage', 'p' => '/lager/varekort.php'),
		'lager/stykliste.php' => array('m' => 'lager', 'l' => '|Stykliste', 'p' => '/lager/varekort.php'),
		'lager/vareproduktion.php' => array('m' => 'lager', 'l' => '|Vareproduktion', 'p' => '/lager/varekort.php'),
		'lager/batch_oversigt.php' => array('m' => 'lager', 'l' => '5004|Batch oversigt', 'p' => '/lager/varekort.php'),
		'lager/stockLog.php' => array('m' => 'lager', 'l' => '3295|Lagerhistorik', 'p' => '/lager/varekort.php'),
		'lager/productCardIncludes/stockLog.php' => array('m' => 'lager', 'l' => '3295|Lagerhistorik', 'p' => '/lager/varekort.php'),
		'lager/modtageliste.php' => array('m' => 'lager', 'l' => '963|Modtageliste', 'p' => ''),
		'lager/modtagelse.php' => array('m' => 'lager', 'l' => '610|Varemodtagelse', 'p' => '/lager/modtageliste.php'),
		'lager/rapport.php' => array('m' => 'lager', 'l' => '3361|Varerapporter', 'p' => ''),
		'lager/lagerstatus.php' => array('m' => 'lager', 'l' => '992|Lagerstatus', 'p' => '/lager/rapport.php'),
		'lager/varespor.php' => array('m' => 'lager', 'l' => '2236|Varespor', 'p' => '/lager/lagerstatus.php'),
		'lager/minmaxstock.php' => array('m' => 'lager', 'l' => '993|Beholdningsrapport', 'p' => '/lager/rapport.php'),
		'lager/optalling.php' => array('m' => 'lager', 'l' => '1956|Lageroptælling', 'p' => '/lager/rapport.php'),
		'lager/pricelist.php' => array('m' => 'lager', 'l' => '2082|Prisliste', 'p' => '/lager/rapport.php'),
		'lager/salg_rapport.php' => array('m' => 'lager', 'l' => '3360|Salg pr. postnummer', 'p' => '/lager/rapport.php'),
		'lager/udlobsrapport.php' => array('m' => 'lager', 'l' => '5014|Udløbsrapport', 'p' => '/lager/rapport.php'),
		// produktion/
		'produktion/ordreliste.php' => array('m' => 'produktion', 'l' => '107|Ordrer', 'p' => ''),
		'produktion/ordre.php' => array('m' => 'produktion', 'l' => '1260|Produktionsordre', 'p' => '/produktion/ordreliste.php'),
		// systemdata/
		'systemdata/kontoplan.php' => array('m' => 'finans', 'l' => '113|Kontoplan', 'p' => ''),
		'systemdata/kontokort.php' => array('m' => 'finans', 'l' => '443|Kontokort', 'p' => '/systemdata/kontoplan.php'),
		'systemdata/formularkort.php' => array('m' => 'system', 'l' => '573|Formularkort', 'p' => ''),
		'systemdata/formeditor.php' => array('m' => 'system', 'l' => '|Formulareditor', 'p' => '/systemdata/formularkort.php'),
		'systemdata/logoupload.php' => array('m' => 'system', 'l' => '1745|Indlæs fil', 'p' => '/systemdata/formularkort.php'),
		'systemdata/regnskabskort.php' => array('m' => 'system', 'l' => '1215|Regnskabskort', 'p' => ''),
		'systemdata/syssetup.php?valg=debitor' => array('m' => 'system', 'l' => '771|Debitor-/kreditorgrupper', 'p' => '', 'q' => array('valg' => 'debitor')),
		'systemdata/diverse.php?sektion=api_valg' => array('m' => 'system', 'l' => '5537|Integrationer', 'p' => '', 'q' => array('sektion' => 'api_valg')),
		'systemdata/tekster.php' => array('m' => 'system', 'l' => '581|Tekster', 'p' => ''),
		'systemdata/personalSettings.php' => array('m' => 'system', 'l' => '5500|Personlige indstillinger', 'p' => ''),
		'systemdata/importer_kontoplan.php' => array('m' => 'system', 'l' => '6652|Importér kontoplan', 'p' => ''),
		'systemdata/importer_varianter.php' => array('m' => 'system', 'l' => '6839|Importér varianter fra CSV', 'p' => ''),
		'systemdata/importAccountMap.php' => array('m' => 'system', 'l' => '2336|Importer mappingfil til offentlig standard kontoplan', 'p' => ''),
		'systemdata/exporter_kontoplan.php' => array('m' => 'system', 'l' => '1353|Eksportér kontoplan', 'p' => ''),
		'systemdata/exporter_adresser.php' => array('m' => 'system', 'l' => '1384|Eksporter adresser', 'p' => ''),
		'systemdata/importer_adresser.php' => array('m' => 'system', 'l' => '1385|Importer_adresser', 'p' => ''),
		'systemdata/exporter_varer.php' => array('m' => 'system', 'l' => '1383|Eksporter varer', 'p' => ''),
		'systemdata/importer_varer.php' => array('m' => 'system', 'l' => '1380|Importér varer', 'p' => ''),
		'systemdata/exporter_variantvarer.php' => array('m' => 'system', 'l' => '1375|Eksporter variantvarer', 'p' => ''),
		'systemdata/importer_variantvarer.php' => array('m' => 'system', 'l' => '1371|Importer_variantvarer', 'p' => ''),
		'systemdata/importer_varelokationer.php' => array('m' => 'system', 'l' => '6659|Importér varelokationer', 'p' => ''),
		'systemdata/exporter_formular.php' => array('m' => 'system', 'l' => '1374|Eksporter formularer', 'p' => ''),
		'systemdata/importer_formular.php' => array('m' => 'system', 'l' => '1367|Importer_formularer', 'p' => ''),
		'systemdata/exporter_posmenu.php' => array('m' => 'system', 'l' => '1932|Eksportér POS-menuer', 'p' => ''),
		'systemdata/importer_posmenu.php' => array('m' => 'system', 'l' => '1934|Importér POS-menuer', 'p' => ''),
		// includes/
		'includes/documents.php?source=kassekladde' => array('m' => 'finans', 'l' => '1408|Kassebilag', 'p' => '/finans/kassekladde.php', 'q' => array('source' => 'kassekladde')),
		'includes/documents.php?source=debitorOrdrer' => array('m' => 'debitor', 'l' => '1408|Kassebilag', 'p' => '/debitor/ordre.php', 'q' => array('source' => 'debitorOrdrer')),
		'includes/documents.php?source=creditorOrder' => array('m' => 'kreditor', 'l' => '1408|Kassebilag', 'p' => '/kreditor/ordre.php', 'q' => array('source' => 'creditorOrder')),
		'includes/bilag.php' => array('m' => 'debitor', 'l' => '1408|Kassebilag', 'p' => '/debitor/historikkort.php'),
		'includes/salgsstat.php?art=D' => array('m' => 'debitor', 'l' => '922|Salgstatsstik', 'p' => '/debitor/rapport.php', 'q' => array('art' => 'D')),
		'includes/salgsstat.php?art=K' => array('m' => 'kreditor', 'l' => '922|Salgstatsstik', 'p' => '/kreditor/rapport.php', 'q' => array('art' => 'K')),
		'includes/udlign_openpost.php' => array('m' => 'debitor', 'l' => '2189|Udlign åbne poster', 'p' => '/debitor/rapport.php'),
		'includes/prislister.php' => array('m' => 'debitor', 'l' => '1877|Vareimport', 'p' => '/debitor/ordre.php'),
		'includes/ret_transaktion.php' => array('m' => 'finans', 'l' => '|Ret transaktion', 'p' => '/finans/kontrolspor.php'),
		// rental/
		'rental/index.php?vare' => array('m' => 'booking', 'l' => '2137|Udlejningsoversigt', 'p' => '', 'q' => array('vare' => '')),
		'rental/index.php' => array('m' => 'booking', 'l' => '2138|Daglig oversigt', 'p' => ''),
		'rental/settings.php' => array('m' => 'booking', 'l' => '122|Indstillinger', 'p' => ''),
		'rental/daysoff.php' => array('m' => 'booking', 'l' => '2140|Lukkedage', 'p' => ''),
		'rental/items.php' => array('m' => 'booking', 'l' => '2141|Udlejningsvare', 'p' => ''),
		'rental/remote.php' => array('m' => 'booking', 'l' => '2143|Ekstern booking', 'p' => ''),
		'rental/lookupcust.php' => array('m' => 'booking', 'l' => '2142|Søg kundehistorik', 'p' => ''),
		'rental/booking.php' => array('m' => 'booking', 'l' => '|Ny booking', 'p' => '/rental/index.php?vare'),
		'rental/edit.php' => array('m' => 'booking', 'l' => '|Rediger booking', 'p' => '/rental/index.php?vare'),
		// bordplaner/
		'bordplaner/bordplan.php' => array('m' => 'pos', 'l' => '|Bordplan', 'p' => '/debitor/pos_ordre.php'),
		'bordplaner/table_plan.php' => array('m' => 'pos', 'l' => '|Bordplan', 'p' => '/debitor/pos_ordre.php'),
		// sager/
		'sager/sager.php' => array('m' => 'sager', 'l' => '2774|Sager', 'p' => ''),
		'sager/sager.php?funktion=vis_sag' => array('m' => 'sager', 'l' => '2792|Sag', 'p' => '/sager/sager.php', 'q' => array('funktion' => 'vis_sag')),
		'sager/sager.php?funktion=ret_sag' => array('m' => 'sager', 'l' => '2960|Sagsinfo', 'p' => '/sager/sager.php?funktion=vis_sag', 'q' => array('funktion' => 'ret_sag')),
		'sager/planlaeg.php' => array('m' => 'sager', 'l' => '2775|Planlægning', 'p' => ''),
		'sager/planlaeg_beregning.php' => array('m' => 'sager', 'l' => '3209|Planlægning: beregning', 'p' => '/sager/planlaeg.php'),
		'sager/planlaeg_opgaver.php' => array('m' => 'sager', 'l' => '3215|Planlægning: opgaver', 'p' => '/sager/planlaeg.php'),
		'sager/planlaeg_sager.php' => array('m' => 'sager', 'l' => '3222|Planlægning: sager', 'p' => '/sager/planlaeg.php'),
		'sager/planlaeg_sag.php' => array('m' => 'sager', 'l' => '2983|Planlægning af sag', 'p' => '/sager/sager.php?funktion=vis_sag'),
		'sager/kontrol_sager.php' => array('m' => 'sager', 'l' => '3186|Kontrolskema', 'p' => '/sager/sager.php?funktion=vis_sag'),
		'sager/bilag_sager.php' => array('m' => 'sager', 'l' => '671|Bilag', 'p' => '/sager/sager.php?funktion=vis_sag'),
		'sager/tilbud.php' => array('m' => 'sager', 'l' => '812|Tilbud', 'p' => '/sager/sager.php?funktion=vis_sag'),
		'sager/template_list.php' => array('m' => 'sager', 'l' => '3241|Opret/ret skabeloner', 'p' => '/sager/tilbud.php'),
		'sager/template_form.php' => array('m' => 'sager', 'l' => '3239|Ret skabelon', 'p' => '/sager/template_list.php'),
		'sager/notat.php' => array('m' => 'sager', 'l' => '2776|Dagbog', 'p' => ''),
		'sager/kunder.php' => array('m' => 'sager', 'l' => '991|Kunder', 'p' => ''),
		'sager/kunder.php?funktion=ret_kunde' => array('m' => 'sager', 'l' => '2961|Kundekort', 'p' => '/sager/kunder.php', 'q' => array('funktion' => 'ret_kunde')),
		'sager/certificering.php' => array('m' => 'sager', 'l' => '2777|Certificering', 'p' => ''),
		'sager/kontrolskemaer.php' => array('m' => 'sager', 'l' => '3157|Kontrolskemaer', 'p' => '/sager/certificering.php'),
		'sager/medarbejdermappe.php' => array('m' => 'sager', 'l' => '2779|Medarbejdermappe', 'p' => ''),
		'sager/mm_kontrolskemaer.php' => array('m' => 'sager', 'l' => '3157|Kontrolskemaer', 'p' => '/sager/medarbejdermappe.php'),
		'sager/bilag_mappe.php' => array('m' => 'sager', 'l' => '1411|Vedhæft bilag', 'p' => '/sager/medarbejdermappe.php'),
		'sager/bilag_ansatmappe.php' => array('m' => 'sager', 'l' => '1411|Vedhæft bilag', 'p' => '/sager/medarbejdermappe.php'),
		'sager/loen.php' => array('m' => 'loen', 'l' => '2784|Løn', 'p' => ''),
		'sager/loen.php?funktion=ret_loen' => array('m' => 'loen', 'l' => '2785|Lønindtastning', 'p' => '/sager/loen.php', 'q' => array('funktion' => 'ret_loen')),
		'sager/loen.php?funktion=loenafregning' => array('m' => 'loen', 'l' => '2786|Lønafregning', 'p' => '/sager/loen.php', 'q' => array('funktion' => 'loenafregning')),
		'sager/ansatte.php' => array('m' => 'loen', 'l' => '1262|Ansatte', 'p' => '/sager/loen.php'),
	),
);
